version: '3'

services: 
  db: 
    image: mysql/mysql-server
    container_name: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    ports:
      - '3306:3306'  #host物理直接映射端口为3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
      MYSQL_USER: yxl   #创建jeese用户
      MYSQL_PASSWORD: 123456  #设置jeese用户的密码
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "/usr/local/software/mysql/mysql-init:/docker-entrypoint-initdb.d"  #设置数据库自动执行脚本目录，目录要存在
  web: 
    build: .
    container_name: aspnetcore
    ports:
      - '8003:80'  #host物理直接映射端口为3306
    depends_on: 
      - db